### ISSUE TITLE
$wgContLang update

### ISSUE THREAD

**Issue by homu9** [JLTRY/NiceCategoryList3#1]
According to:
https://www.mediawiki.org/wiki/Manual:$wgContLang

Add
`use MediaWiki\MediaWikiServices;`
and replace
`$wgContLang`
with
`MediaWikiServices::getInstance()->getContentLanguage()`

I was updating MediaWiki today and lucky to see this repo updated 8 hours ago.
Sorry to submit an issue like this, I'm not familiar with git, don't want to pollute the code.

**Comment by JLTRY** [comment]
corrected with commit c8c17666291c9e726fe54c07e5c3ffeafcec0b40
