### ISSUE TITLE
extension.json parameters

### ISSUE THREAD

**Issue by surak1961** [JLTRY/NiceCategoryList3#3]
I found your extension named as "Semantic Mediawiki" on Special:Version. Poking into the setup, I found some weird entries in extension.json:
- "name" was set correctly, but "namemsg" was set to "smw-title" --> this seems to be the origin of the issue, and since there is no .i18n file, the setting can probably be left off
- "descriptionmsg" was set with a string valid for "description", resulting in additional brackets {} being displayed

**Comment by JLTRY** [comment]
corrected with commit[ ccd21b](https://github.com/JLTRY/NiceCategoryList3/commit/0ccd21b78873427c807b0eebdfa441cfaba9d49d)
